relpol/relpol/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^relpolapp/', include('relpolapp.urls', namespace="relpolapp")),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

relpol/relpolapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login', views.LoginView.as_view(), name='login'),
    url(r'^signup', views.SignUpView.as_view(), name='signup'),
    url(r'^forgot-password', views.ForgotCredentialsView.as_view(), name='forgot_password'),
    url(r'^forgot-username', views.ForgotCredentialsView.as_view(), name='forgot_username'),
]

relpol/relpolapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# database models for the relpol app


class MainTopic(models.Model):
    """List of main topics:
    Friends and Family
    Dating
    Work and Business"""
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return "Main Topic: " + self.name



class SubTopic(models.Model):
    main_topic = models.ForeignKey(MainTopic)
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return "Sub Topic: " + self.name


class Picture(models.Model):
    picture_file = models.FilePathField(path="/home/yuhwei/RelPol/relpol/relpolapp/static/relpolapp/pictures/", max_length=200)

    def __unicode__(self):
        return "Picture filepath: " + self.picture_file

class BlogPost(models.Model):
    name = models.CharField(max_length=200)
    keyword1 = models.CharField(max_length=200)
    keyword2 = models.CharField(max_length=200)
    keyword3 = models.CharField(max_length=200)
    content_file = models.FilePathField(path="/home/yuhwei/RelPol/relpol/relpolapp/static/relpolapp/blogposts/", max_length=200)
    sub_topic = models.ForeignKey(SubTopic)
    picture = models.ForeignKey(Picture)


    def __unicode__(self):
        return "Blog Post: " + self.name + " Path: " + self.content_file


class FeaturedArticle(models.Model):
    blog_post = models.ForeignKey(BlogPost)


    def __unicode__(self):
        return "Featured Article: " + str(self.blog_post)


class Advertisement(models.Model):
    link = models.URLField(max_length=200)
    picture = models.ForeignKey(Picture, on_delete=models.CASCADE)

    def __unicode__(self):
        return "Advertisement: " + self.link



class Comment(models.Model):
    post_datetime = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=500)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="commenter")
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    in_reply_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="inreplyto")


    def __unicode__(self):
        return "Comment by userId: " + str(self.user) + "\n" + comment 

relpol/relpolapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import FormView
#from django.core.urlresolvers import reverse_lazy

from . import myforms


def index(request):
    return render(request, 'relpolapp/index.html')


class LoginView(FormView):
    template_name = 'relpolapp/login.html'
    form_class = myforms.LoginForm
    success_url = '/relpolapp'


class SignUpView(FormView):
    template_name = 'relpolapp/signup.html'
    form_class = myforms.SignUpForm
    success_url = '/relpolapp'


class ForgotCredentialsView(FormView):
    template_name = 'relpolapp/forgot.html'
    form_class = myforms.ForgotCredentialsForm
    success_url = '/relpolapp'
    

relpol/relpolapp/templates/relpolapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Relationship Politics">
    <meta name="author" content="Yu-Hwei Chou">
    <link rel="icon" href="{% static "relpolapp/pictures/favicon.ico" %}">

    <!-- This doesn't work when placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<!-- Bootstrap core CSS -->
<link href="{% static "relpolapp/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- script for updating active link in navbar -->
<script>

var loc_name = location.pathname;

var dotIndex = loc_name.indexOf('.');

var pName = loc_name.substring(0,dotIndex);
$('.actlink').toggleClass("active",function(){
    if (pName === $(this).attr('href'))
    {
        return True;
    }
    return False;
}
    );
</script>


    <title>Relationship Politics</title>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    [endif]-->

    <!-- Custom styles for this template -->
    <link href="{% static "relpolapp/carousel.css" %}" rel="stylesheet">
    <style>
        .navbar-nav li.welcome-user {
            position: absolute;
            right:20px;}
        html{
            position: relative;
            min-height: 100%;
            }
        body{
            margin-bottom:60px;
            }
        .footer {
          position: absolute;
          bottom: 0;
          width: 100%;
          /* Set the fixed height of the footer here */
          height: 60px;
          background-color: #f5f5f5;
                }
    </style>

    {% block head %}
    {% endblock %}
  </head>
<!-- NAVBAR
================================================== -->
  <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand actlink" href="{% url 'relpolapp:login' %}">Login</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active actlink"><a href="{% url 'relpolapp:index' %}">Home</a></li>
                <li class="actlink"><a href="#about">About</a></li>
                <li class="actlink"><a href="#contact">Contact</a></li>
                <li class="dropdown actlink">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
                <li class="welcome-user"><a href="profile">Welcome!</a></li>
              </ul>
            </div>
          </div>
        </nav>

        {% block maincontent %}
        {% endblock %}

     <footer class="footer">
      <div class="container">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2015 Relationship Politics &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </div>
    </footer>
</body>
</html>

relpol/relpolapp/templates/relpolapp/index.html
{% extends 'relpolapp/base.html' %}

{% load staticfiles %}
{% block maincontent %}

    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static "relpolapp/pictures/PIGGIES.jpg" %}" alt="First slide" style="width: 100%;">
          <div class="container">
            <div class="carousel-caption">
              <h1>Work and Business</h1>
              <p>Find out how to make workplace relationships work for you.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Friends and Family</h1>
              <p>Unconditional love can go pretty far, but conflicts with close ones need to be handled with care.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Dating</h1>
              <p>Trying to turn a complete stranger into your most intimate partner? How hard could that be?</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>What's your relationship personality?</h2>
          <p>Research shows that one type of personality dominates in upper management. Do you have it?</p>
          <p><a class="btn btn-default" href="#" role="button">Take the Test &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Love comes first</h2>
          <p>Whether it's common marital conflicts or rebellious offspring, read on for out take on how to succeessfully resolve issues with those you hold dear.</p>
          <p><a class="btn btn-default" href="#" role="button">Family Articles &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>The dating game</h2>
          <p>Ever been on a date and felt like you were being interviewed for a job? How do you know you've found the one? Just want to chuckle at some dating horror stories? Click the button below!</p>
          <p><a class="btn btn-default" href="#" role="button">Dating Articles &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->



    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "relpolapp/assets/js/ie10-viewport-bug-workaround.js" %}"></script>
    {% endblock %}

relpol/relpolapp/templates/relpolapp/login.html
{% extends 'relpolapp/base.html' %}
{% block head %}
<style>
    .container-marketing{
        position:relative;
        top: 150px;
        left: 80px;
        }
    .inputbutton
    {
        margin-left:auto;
    }
</style>
{% endblock %}
{% load staticfiles %}
{% block maincontent %}

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container-marketing" >

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
           <form action="" method="post">{% csrf_token %}
               {{ form.as_p }}
           <input class=inputbutton type="submit" value="Login" />
           </form>
        </div><!-- /.col-lg-4 -->
        </div>


    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "relpolapp/assets/js/ie10-viewport-bug-workaround.js" %}"></script>
    {% endblock %}